### ISSUE TITLE
installation error on windows .

### ISSUE THREAD

**Issue by Umar-Juraev** [kybarg/ebds#4]
Node v18.3.0
npm v8.19.3

issue : How can i solve it without installation python ?

Thank you in advance!

npm ERR! command failed 
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild 
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.12.1 runtime=node arch=x64 libc= platform=win32) 
npm ERR! gyp info it worked if it ends with ok 
npm ERR! gyp info using node-gyp@9.1.0 
npm ERR! gyp info using node@18.12.1 | win32 | x64 
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration 
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON 
npm ERR! gyp ERR! find Python checking if "python3" can be used 
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an errornpm ERR! gyp ERR! find Python checking if "python" can be used 
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error  
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Kartomat\AppData\Local\Programs\Python\Python39\python.exe 
npm ERR! gyp ERR! find Python - "C:\Users\Kartomat\AppData\Local\Programs\Python\Python39\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could  
not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Kartomat\AppData\Local\Programs\Python\Python39-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Users\Kartomat\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Kartomat\AppData\Local\Programs\Python\Python38\python.exe 
npm ERR! gyp ERR! find Python - "C:\Users\Kartomat\AppData\Local\Programs\Python\Python38\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could  
not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Kartomat\AppData\Local\Programs\Python\Python38-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Users\Kartomat\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Kartomat\AppData\Local\Programs\Python\Python37\python.exe 
npm ERR! gyp ERR! find Python - "C:\Users\Kartomat\AppData\Local\Programs\Python\Python37\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python37\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files\Python37\python.exe" could  
not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Kartomat\AppData\Local\Programs\Python\Python37-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Users\Kartomat\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python37-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files\Python37-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run 
npm ERR! gyp ERR! find PythonGitHub - nodejs/node-gyp: Node.js native addon build tool
Node.js native addon build tool. Contribute to nodejs/node-gyp development by creating an account on GitHub.

checking if Python is C:\Users\Kartomat\AppData\Local\Programs\Python\Python36\python.exe 
npm ERR! gyp ERR! find Python - "C:\Users\Kartomat\AppData\Local\Programs\Python\Python36\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python36\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files\Python36\python.exe" could  
not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Kartomat\AppData\Local\Programs\Python\Python36-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Users\Kartomat\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python36-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files\Python36-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe 
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run 
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python 3 
npm ERR! gyp ERR! find Python - "py.exe" is not in PATH or produced an error  
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python ****************************************************** 
npm ERR! gyp ERR! find Python You need to install the latest version of Python. 
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not, 
npm ERR! gyp ERR! find Python you can try one of the following options:       
npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe" 
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm) 
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON 
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:    
npm ERR! gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"npm ERR! gyp ERR! find Python For more information consult the documentation  
at: 
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installationnpm ERR! gyp ERR! find Python ****************************************************** 
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error  
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use  
npm ERR! gyp ERR! stack     at PythonFinder.fail (C:\Users\Kartomat\AppData\Roaming\nvm\v18.12.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:330:47) 
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (C:\Users\Kartomat\AppData\Roaming\nvm\v18.12.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:159:21) 
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Kartomat\AppData\Roaming\nvm\v18.12.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:228:18) 
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\Kartomat\AppData\Roaming\nvm\v18.12.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:294:16) 
npm ERR! gyp ERR! stack     at exithandler (node:child_process:420:5)         
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:432:5) 
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)         
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12) 
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
npm ERR! gyp ERR! System Windows_NT 10.0.19045 
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kartomat\\AppData\\Roaming\\nvm\\v18.12.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" 
npm ERR! gyp ERR! cwd C:\Users\Kartomat\Desktop\kms-terminal\node_modules\@serialport\bindings 
npm ERR! gyp ERR! node -v v18.12.1 
npm ERR! gyp ERR! node-gyp -v v9.1.0 
npm ERR! gyp ERR! not ok 
 
npm ERR! A complete log of this run can be found in: 
npm ERR!     C:\Users\Kartomat\AppData\Local\npm-cache\_logs\2023-03-07T

**Comment by kybarg** [comment]
@Umar-Juraev unfortnately no other way. This packages uses [serialport](https://serialport.io/) package which has native bindings and requires building for trarget os.
